/* ADDITIONAL STATES */
export const questionPool = [
  { word: "A", probability: 0.6 },
  { word: "B", probability: 0.6 },
  { word: "C", probability: 0.4 },
  { word: "E", probability: 0.4 },
  { word: "G", probability: 0.2 },
  { word: "H", probability: 0.2 },
  { word: "I", probability: 0.5 },
  { word: "J", probability: 0.5 },
  { word: "K", probability: 0.3 },
  { word: "L", probability: 0.8 },
  { word: "O", probability: 0.4 },
  { word: "R", probability: 0.3 },
  { word: "S", probability: 0.4 },
  { word: "T", probability: 0.3 },
  { word: "U", probability: 0.2 },
  { word: "V", probability: 0.3 },
  { word: "W", probability: 0.5 },
  { word: "X", probability: 0.3 },
  { word: "Y", probability: 0.6 },
  { word: "Thank you", probability: 0.7 },
  { word: "Sorry", probability: 0.2 },
  { word: "Please", probability: 0.4 },
  { word: "Hello", probability: 0.8 },
  { word: "I / Me", probability: 0.4 },
  { word: "Us", probability: 0.6 },
  { word: "My", probability: 0.7 },
  { word: "Do", probability: 0.4 },
  { word: "Go", probability: 0.2 },
  { word: "Busy", probability: 0.5 },
  { word: "Food", probability: 0.5 },
];

export const arabicQuesions = [
  { word: "ع", probability: 0.7 },
  { word: "ال", probability: 0.7 },
  { word: "ا", probability: 0.6 },
  { word: "ب", probability: 0.6 },
  { word: "ض", probability: 0.3 },
  { word: "د", probability: 0.3 },
  { word: "ف", probability: 0.6 },
  { word: "ح", probability: 0.2 },
  { word: "ه", probability: 0.2 },
  { word: "ج", probability: 0.2 },
  { word: "خ", probability: 0.3 },
  { word: "لا", probability: 0.6 },
  { word: "ل", probability: 0.4 },
  { word: "م", probability: 0.7 },
  { word: "ن", probability: 0.8 },
  { word: "ق", probability: 0.7 },
  { word: "ر", probability: 0.7 },
  { word: "ص", probability: 0.5 },
  { word: "س", probability: 0.5 },
  { word: "ش", probability: 0.6 },
  { word: "ط", probability: 0.4 },
  { word: "ذ", probability: 0.5 },
  { word: "ث", probability: 0.1 },
  { word: "ي", probability: 0.1 },
  { word: "ز", probability: 0.8 },
];
